### ISSUE TITLE
save settings on exit

### ISSUE THREAD

**Issue by smaragdus** [tualatin/winmd5checksum#17]
It would be convenient if the program saves some basic settings on exit in program folder (to retain portability), for example:

- Active algorithms;
- Always on top;

Currently (as of version [1.5.6775](https://github.com/tualatin/winmd5checksum/releases/tag/1.5.6775)) after I restart the program I have always to activate SHA512 manually and to select "Always on top"- if the program remembers last used settings the user would be spared some extra clicks.

**Comment by tualatin** [comment]
Thank you for your hint. In progress.

**Comment by smaragdus** [comment]
@tualatin 
This was really fast, thanks!
