### ISSUE TITLE
copy selected hash

### ISSUE THREAD

**Issue by smaragdus** [tualatin/winmd5checksum#19]
I will appreciate an easy way to copy selected hash (without using '**Save hash**' command), screen:

![winmd5checksum 1 5 6775 - 2018-07-26 - 004](https://user-images.githubusercontent.com/9025757/43262055-753eb91c-90e7-11e8-94c2-12dabd8168c7.png)

In short:

- 'Double click' on generated hash allows 'Ctrl+C' (like ' Hash to compare' box);
- 'Copy' button next to 'Hash algorithm' which copies hash value;
- 'Double click' on generated hash automatically copies hash value;

I hope I am not missing something but I don't find a way of copying hashes without saving.

**Comment by tualatin** [comment]
Fixed, inside the column is a button, to copy the current selected hash into the Clipboard.

**Comment by smaragdus** [comment]
I saw the [screen-shot](https://user-images.githubusercontent.com/1204300/43318654-d91c5736-91a1-11e8-9ac4-676c05225560.jpg), it looks fine, thanks.
